# Generated by Django 3.2.9 on 2021-11-05 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='new_user',
        ),
    ]
