# Generated by Django 3.2.9 on 2021-11-05 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0002_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='DBapp_user',
        ),
    ]
