# Generated by Django 3.2.9 on 2021-11-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0003_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usernanme',
            field=models.CharField(max_length=32, verbose_name='사용자명'),
        ),
    ]
