# Generated by Django 3.2.9 on 2021-11-05 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0004_alter_user_usernanme'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='user_c',
        ),
    ]
