# Generated by Django 3.2.9 on 2021-11-05 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0006_rename_usernanme_user_c_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_c',
            options={'verbose_name': '사용자_구매자', 'verbose_name_plural': '사용자_구매자'},
        ),
    ]
